name: Jira Transition to InProgress

on:
  create:
    branches:
      - 'feat/**'
      - 'fix/**'
      - 'hotfix/**'

jobs:
  jiraTicketToInProgress:
    name: Transition Issue to In Progress
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find in Jira ticket
      uses: atlassian/gajira-find-issue-key@master
      id: jira-ticket
      with:
        string: ${{ github.event.ref }}

    - name: Transition issue to Done
      if: steps.jira-ticket.outputs.issue != ''
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.jira-ticket.outputs.issue }}
        transition: "In Progress"
